project:
  type: website
  output-dir: docs

website:
  title: "Tekst og tal"
  navbar:
    left:
      - href: about.qmd
        text: Lasse
      - href: index.qmd
      - href: nonfiktion.qmd
      - href: fiktion.qmd
  open-graph: true

format:
  html:
    theme: litera
    css: styles.css
    toc: false
