project:
  type: website
  output-dir: docs

website:
  title: "Tekst og tal"
  navbar:
    left:
      - href: index.qmd
        text: Om
      - href: nonfiktion.qmd
      - href: fiktion.qmd

format:
  html:
    theme: litera
    css: styles.css