project:
  type: website
  output-dir: docs

website:
  title: "Tekst og tal"
  navbar:
    left:
      - href: index.qmd
        text: Hej
      - href: about.qmd
      - href: nonfiktion.qmd
      - href: fiktion.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true