project:
  type: website
  output-dir: docs

website:
  title: "Tekst og tal"
  navbar:
    left:
      - href: index.qmd
        text: Lasse
      - href: nonfiktion.qmd
        text: Nonfiktion
      - href: fiktion.qmd
        text: Fiktion
      - href: datascience.qmd
        text: Data Science
      - href: foredrag.qmd
        text: Foredrag
  open-graph: true

format:
  html:
    theme: litera
    css: styles.css
    toc: false
    
    