---
title: "Eksempler på foredrag"
---

Jeg holder nu og da foredrag, her er nogle eksempler:

-   **Er statistik, big data og kunstig intelligens the shit?**\
    Hvordan kan statistik, matematik og klædelig videnskabelig ydmyghed bruges som udgangspunkt for datajournalistiske fortællinger?\
    *Oplæg for journalistnetværk om vidensbaseret journalistik, juni 2021.* Se [slides](presentations/statistik-journalistik.html).

-   **Data, journalistik og aha-oplevelser**\
    Målet med datajournalistik er, ifølge Lasse Hjorth Madsen, at bruge aha-oplevelsen som motor for en god læseoplevelse og samtidig højne forståelsen for grundlæggende databaseret, videnskabelig tankegang.\
*Oplæg i forbindelse med bibliotekernes projekt, [DataDemocracy](https://datademocracy.dk/), maj 2021*. Se [slides](presentations/data-demokrati-journalistik.html).

-   **Kan en algoritme anbefale bøger?**\
Forfatter og data scientist Lasse Hjorth Madsen taler om, hvordan man ved hjælp af algoritmer kan finde frem til sine nye yndlingsbøger og udpeger perspektiverne i at analysere menneskers særlige smag ved hjælp af data.\
*eReolens efterårskonference, november 2020*. Se [slides](presentations/ereolen_talk_2020.html).

-   **Data science og tekstanalyse i praksis **\
Oplæg for studerende på den nyoprettede uddannelse i [social data science](https://studies.ku.dk/masters/social-data-science/) om hvordan data science og NLP kan bruges i praksis i erhvervslivet.\
*Københavns Universitet, septempber 2020*. Se [slides](presentations/social_data_science_talk.html).
